// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoReservas.Models;

#nullable disable

namespace ProyectoReservas.Migrations
{
    [DbContext(typeof(ReservasContext))]
    [Migration("20240109024240_Reservas")]
    partial class Reservas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoReservas.Models.Entidades.Cliente", b =>
                {
                    b.Property<int>("idcliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idcliente"));

                    b.Property<string>("apellidoC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idcliente");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("ProyectoReservas.Models.Entidades.Empleado", b =>
                {
                    b.Property<int>("idempleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idempleado"));

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idempleado");

                    b.ToTable("empleados");
                });

            modelBuilder.Entity("ProyectoReservas.Models.Entidades.Mesa", b =>
                {
                    b.Property<int>("idmesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idmesa"));

                    b.Property<int>("capacidad")
                        .HasColumnType("int");

                    b.Property<int>("numero_mesa")
                        .HasColumnType("int");

                    b.HasKey("idmesa");

                    b.ToTable("mesas");
                });

            modelBuilder.Entity("ProyectoReservas.Models.Entidades.Reserva", b =>
                {
                    b.Property<int>("idreserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idreserva"));

                    b.Property<DateTime>("FechaHoraLlegada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraReserva")
                        .HasColumnType("datetime2");

                    b.Property<int>("clienteid")
                        .HasColumnType("int");

                    b.Property<int>("empleadoid")
                        .HasColumnType("int");

                    b.Property<int>("mesaid")
                        .HasColumnType("int");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idreserva");

                    b.HasIndex("clienteid");

                    b.HasIndex("empleadoid");

                    b.HasIndex("mesaid");

                    b.ToTable("reservas");
                });

            modelBuilder.Entity("ProyectoReservas.Models.Entidades.Reserva", b =>
                {
                    b.HasOne("ProyectoReservas.Models.Entidades.Cliente", "idcliente")
                        .WithMany()
                        .HasForeignKey("clienteid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoReservas.Models.Entidades.Empleado", "idempleado")
                        .WithMany()
                        .HasForeignKey("empleadoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoReservas.Models.Entidades.Mesa", "idmesa")
                        .WithMany()
                        .HasForeignKey("mesaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("idcliente");

                    b.Navigation("idempleado");

                    b.Navigation("idmesa");
                });
#pragma warning restore 612, 618
        }
    }
}
